### ISSUE TITLE
点击确定等按钮后，能否不让自动关闭弹窗

### ISSUE THREAD

**Issue by jsoncode** [sufangyu/dialog2#10]
有这样一个需求，按钮事件的回掉结果由自己来处理，点击任何按钮之后，不要关闭弹窗，让开发者自己调用close方法来关闭。
或者作者大大已经实现，只是没提供api?

**Comment by sufangyu** [comment]
@jsoncode 这个没实现，这2天抽空实现后更新版本。

**Comment by sufangyu** [comment]
@jsoncode 这功能已经实现，在回调函数返回 false 就可以阻止弹窗的关闭。
