### ISSUE TITLE
触摸事件

### ISSUE THREAD

**Issue by LichiaMa** [sufangyu/dialog2#3]
你好，我用了下你的插件，出现了一个问题
![image](https://cloud.githubusercontent.com/assets/17775060/23147394/8834e6b2-f819-11e6-9d6e-36226b4fe6c7.png)
请问这个是为什么啊

**Comment by DoubleRayWang** [comment]
同样的也是出现了这个问题

**Comment by oOBobbyOo** [comment]
![image](https://user-images.githubusercontent.com/12425983/33355095-f959718c-d4f0-11e7-9483-189b258bae41.png)

**Comment by oOBobbyOo** [comment]
![image](https://user-images.githubusercontent.com/12425983/33355124-17966a4c-d4f1-11e7-9e0e-ddebee6d5b9b.png)

**Comment by sufangyu** [comment]
刚刚修复这个问题，重新 clone 使用新版本就行。

**Comment by sufangyu** [comment]
@oOBobbyOo @DoubleRayWang 
刚刚修复这个问题，重新 clone 使用新版本就行。
