### ISSUE TITLE
使用jQuery，点击取消后，不能再次点击怎么解决

### ISSUE THREAD

**Issue by lihuimi** [sufangyu/dialog2#7]

**Comment by sufangyu** [comment]
@lihuimi 麻烦补充上这个问题的相应部分的代码, 好方便了解实际的应用场景

**Comment by lihuimi** [comment]
I'm so sorry to reply you so late, this project is too busy.

Then thank you very much for your reply. This problem has been solved. 
I used jQuery in development, which may be the result of this result that the button cannot be repeated and the zepto is not a problem.


Thanks again.




在 2017-07-13 14:53:01，"方雨_Yu" <notifications@github.com> 写道：


@lihuimi 麻烦补充上这个问题的相应部分的代码, 好方便了解实际的应用场景
